# Generated by Django 6.0.7 on 2026-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bookings_options_alter_bookings_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpireEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Expired Event',
                'verbose_name_plural': 'Expired Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
