# Generated by Django 6.0.7 on 2026-07-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expireevent_event_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seats',
        ),
    ]
