# Generated by Django 6.0.7 on 2026-07-11 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_event_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
